name: Create Issue In Jira

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
  workflow_call:

jobs:
  create_jira_issue:
    name: Create Jira Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    # Create new ticket in Jira
    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: PETOSS
        issuetype: Story
        summary: ${{ github.event.repository.name }} ${{ github.event.issue.number || github.event.pull_request.number }} ${{ github.event.issue.title || github.event.pull_request.title }}
        description: ${{ github.event.issue.body || github.event.pull_request.body }}

   # Add created jira id as comment in issue thread. This allows us to easily 
   # retrieve the id when the issue state is updated, i.e. closed 
    - name: Add jira ticket id as comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
        body: ${{ steps.create.outputs.issue }}
   
   # Add additional comment to let user know what is happening
    - name: Add additional comment notifying user that a ticket has been created
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
        body: Thanks for raising an issue, a ticket has been created to track your request  
