name: PR Linting

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  linting:
    runs-on: ubuntu-latest
    name: MegaLinter Validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/documentation@v9

  commitlint:
    runs-on: ubuntu-latest
    name: Conventional Commit Validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate PR commits with commitlint
        run: |
          npm install --no-save @commitlint/cli @commitlint/config-conventional
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose